"""Provenance records for auto-discovered formulaic alphas.

The brief is explicit: **do not directly trust auto-generated
features**. Every candidate the miner evaluates must be stored with
full provenance so we can audit, reproduce, and replay any decision
the search algorithm made:

- the AST expression that was evaluated
- the seed + generation + parent it came from (lineage)
- the operator-set + feature-set versions at the time of evaluation
- the evaluated evidence (IC, ICIR, turnover, …)
- the admission decision (admitted / rejected + reason)

This module ships the leaf dataclasses; the miner driver in
:mod:`.search` / :mod:`.__init__` is what actually populates them.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datetime import datetime

    from quant_platform.research.features.formulaic.ast import Expression
    from quant_platform.research.features.formulaic.mining.evidence import (
        CandidateEvidence,
    )
    from quant_platform.research.features.formulaic.mining.walk_forward import (
        WalkForwardEvidence,
    )

#: Evidence shape carried on a provenance row. Single-pass mining
#: stores :class:`CandidateEvidence`; walk-forward mining stores
#: :class:`WalkForwardEvidence`. The :class:`AdmissionGate` reads both
#: via field-name compatibility (``rank_ic``, ``icir``, ``turnover``,
#: ``coverage``, ``correlation_to_baseline_max``, ``n_dates``) — the
#: WF type just adds extra fields the gate consults via ``getattr``.
EvidencePayload = "CandidateEvidence | WalkForwardEvidence"


@dataclass(frozen=True)
class AutoAlphaProvenance:
    """Full provenance record for one auto-discovered alpha candidate.

    Attributes
    ----------
    name:
        Stable identifier (e.g. ``auto_alpha_000123``). Generated by
        the miner driver from a monotonically-increasing counter.
    expression:
        The AST that produced the feature column. The single source of
        truth for *what this alpha does* — the name is just a label.
    generation:
        For evolutionary search, the generation index at which this
        candidate was evaluated (0 = initial population). For random
        search, always 0.
    seed:
        Per-run RNG seed. Combined with ``generation`` + the search
        algorithm's deterministic iteration order, the seed reproduces
        the full population that landed in any run.
    parent_name:
        Name of the parent candidate this one was mutated from, or
        ``None`` for seed candidates (initial population / random
        search output).
    mutation_kind:
        The :mod:`.mutation` operator that produced this candidate
        (e.g. ``"swap_operator"``, ``"change_window"``), or ``None``
        for seed candidates.
    operator_set_version:
        Operator catalog version at evaluation time. Pinned so that
        a future change to a registered operator's compute function
        doesn't silently invalidate this row's evidence.
    feature_set_version:
        Feature-set version of the formulaic family at evaluation
        time.
    evidence:
        :class:`CandidateEvidence` from
        :func:`.evidence.compute_evidence`. Carries IC, ICIR,
        turnover, correlation-to-baseline, coverage.
    created_at:
        UTC timestamp at evaluation time. Useful for retired-after
        cutoffs and reproducibility audits.
    admitted:
        Whether :class:`.admission.AdmissionGate` admitted this
        candidate. Defaults to ``False`` until the gate runs.
    admission_reason:
        Human-readable explanation of the admission decision (e.g.
        ``"rank_ic below threshold (0.018 < 0.030)"``).
    notes:
        Free-form tags / observations a human reviewer can append.
        Empty by default.
    """

    name: str
    expression: Expression
    generation: int
    seed: int
    parent_name: str | None
    mutation_kind: str | None
    operator_set_version: str
    feature_set_version: str
    evidence: CandidateEvidence | WalkForwardEvidence
    created_at: datetime
    admitted: bool = False
    admission_reason: str = ""
    notes: tuple[str, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        if not self.name.strip():
            raise ValueError("AutoAlphaProvenance.name must be non-empty")
        if self.generation < 0:
            raise ValueError(
                f"AutoAlphaProvenance({self.name!r}).generation must be >= 0; got {self.generation}"
            )


__all__ = [
    "AutoAlphaProvenance",
]
