"""Backtest tearsheet renderer."""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

import structlog

from quant_platform.services.research_service.reports.tearsheet_sections import (
    render_attribution_section,
    render_equity_section,
    render_execution_quality_section,
    render_ic_section,
    render_industrial_evidence_section,
    render_risk_section,
)

if TYPE_CHECKING:
    import uuid
    from pathlib import Path

log = structlog.get_logger(__name__)


def _load_json(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return dict(payload) if isinstance(payload, dict) else None
    except json.JSONDecodeError:
        log.warning("tearsheet.invalid_json", path=str(path))
        return None


def render_tearsheet(
    run_id: uuid.UUID,
    root: Path,
) -> Path:
    """Render ``<root>/<run_id>/tearsheet.md`` from sidecar artifacts."""
    run_dir = root / str(run_id)
    run_dir.mkdir(parents=True, exist_ok=True)

    ic = _load_json(run_dir / "ic_report.json")
    attribution = _load_json(run_dir / "attribution.json")
    metrics = _load_json(run_dir / "metrics.json")
    run_summary = _load_json(run_dir / "run_summary.json")
    execution_quality = _load_json(run_dir / "execution_quality.json")
    evidence = _load_json(run_dir / "backtest_evidence_manifest.json")
    reconciliation = _load_json(run_dir / "backtest_reconciliation.json")
    if run_summary is not None and not metrics:
        metrics = {"equity_curve": run_summary.get("equity_curve", [])}

    sections = [
        f"# Backtest tearsheet - {run_id}\n",
        "## Risk\n",
        render_risk_section(run_summary),
        "\n## Execution Quality\n",
        render_execution_quality_section(execution_quality),
        "\n## Industrial Evidence\n",
        render_industrial_evidence_section(evidence, reconciliation),
        "\n## Equity curve\n",
        render_equity_section(metrics, root, run_id),
        "\n## Information Coefficient (decay)\n",
        render_ic_section(ic),
        "\n## Attribution\n",
        render_attribution_section(attribution),
        "\n---\n",
        "_Generated by `quant-platform tearsheet`._",
    ]
    path = run_dir / "tearsheet.md"
    path.write_text("\n".join(sections), encoding="utf-8")
    log.info("tearsheet.written", path=str(path))
    return path


__all__ = ["render_tearsheet"]
