"""Build a curated liquid US-equity universe contracts file (no network).

The Polygon reference API on the available key cannot rank liquidity (the
grouped-daily endpoint is rate-limited / unauthorized), so this builder uses a
hand-curated set of liquid US large/mid-cap common stocks grouped by GICS
sector. Every name has continuous 2022-2026 history, which the Tiingo ingest
path then backfills.

``con_id`` is 0 (resolve via a one-time IB ``reqContractDetails`` pass before
live/paper routing) and ``adv_shares_20d`` is a seed value (real ADV is
recomputed from bars during ingest). Sector is GICS-accurate; ``primary_exchange``
is best-effort and does not affect ingest/backfill/campaign.

Usage::

    python scripts/build_universe_curated.py --out infra/config/universe_300.json
"""

from __future__ import annotations

import argparse
import json
import uuid
from pathlib import Path

# Stable namespace shared with build_universe.py so instrument_id UUIDs stay
# stable across the 15-name paper smoke fixture and the expanded universe.
NS = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")

# Curated liquid US large/mid-cap common stocks, keyed by GICS sector.
SECTOR_TICKERS: dict[str, list[str]] = {
    "Information Technology": [
        "AAPL",
        "MSFT",
        "NVDA",
        "AVGO",
        "ORCL",
        "CRM",
        "CSCO",
        "ACN",
        "AMD",
        "ADBE",
        "TXN",
        "QCOM",
        "INTU",
        "IBM",
        "AMAT",
        "NOW",
        "ADI",
        "LRCX",
        "MU",
        "KLAC",
        "SNPS",
        "CDNS",
        "INTC",
        "APH",
        "MSI",
        "ROP",
        "NXPI",
        "MCHP",
        "FTNT",
        "MPWR",
        "CDW",
        "GLW",
        "KEYS",
        "HPQ",
        "HPE",
        "WDC",
        "STX",
        "NTAP",
        "TER",
        "PTC",
        "TDY",
        "GRMN",
        "ADP",
        "PAYX",
    ],
    "Communication Services": [
        "GOOGL",
        "GOOG",
        "META",
        "NFLX",
        "TMUS",
        "DIS",
        "CMCSA",
        "VZ",
        "T",
        "CHTR",
        "EA",
        "TTWO",
        "OMC",
        "IPG",
        "WBD",
        "LYV",
    ],
    "Consumer Discretionary": [
        "AMZN",
        "TSLA",
        "HD",
        "MCD",
        "LOW",
        "NKE",
        "SBUX",
        "BKNG",
        "TJX",
        "ORLY",
        "CMG",
        "MAR",
        "GM",
        "F",
        "HLT",
        "ROST",
        "AZO",
        "YUM",
        "DHI",
        "LEN",
        "NVR",
        "PHM",
        "APTV",
        "GPC",
        "BBY",
        "ULTA",
        "EBAY",
        "EXPE",
        "DRI",
        "LVS",
        "RCL",
        "CCL",
        "POOL",
        "TSCO",
        "KMX",
        "DPZ",
    ],
    "Consumer Staples": [
        "PG",
        "COST",
        "WMT",
        "KO",
        "PEP",
        "PM",
        "MO",
        "MDLZ",
        "CL",
        "TGT",
        "KMB",
        "GIS",
        "SYY",
        "KHC",
        "STZ",
        "KR",
        "HSY",
        "ADM",
        "MNST",
        "KDP",
        "CHD",
        "CLX",
        "MKC",
        "TAP",
        "DG",
        "DLTR",
    ],
    "Health Care": [
        "LLY",
        "UNH",
        "JNJ",
        "ABBV",
        "MRK",
        "TMO",
        "ABT",
        "DHR",
        "PFE",
        "AMGN",
        "ISRG",
        "BMY",
        "MDT",
        "CVS",
        "GILD",
        "CI",
        "ELV",
        "VRTX",
        "REGN",
        "HCA",
        "ZTS",
        "BSX",
        "BDX",
        "HUM",
        "IDXX",
        "IQV",
        "A",
        "MTD",
        "RMD",
        "BIO",
        "WST",
        "DXCM",
        "CNC",
        "ALGN",
        "BAX",
        "COO",
        "ZBH",
        "HOLX",
        "CAH",
        "MCK",
    ],
    "Financials": [
        "JPM",
        "V",
        "MA",
        "BAC",
        "WFC",
        "GS",
        "MS",
        "AXP",
        "SPGI",
        "BLK",
        "C",
        "SCHW",
        "CB",
        "PGR",
        "MMC",
        "PNC",
        "USB",
        "AON",
        "ICE",
        "CME",
        "COF",
        "TFC",
        "BK",
        "AIG",
        "MET",
        "PRU",
        "TRV",
        "AFL",
        "ALL",
        "AMP",
        "GPN",
        "MSCI",
        "NDAQ",
        "DFS",
        "HIG",
        "WTW",
        "MTB",
        "FITB",
        "HBAN",
        "RF",
        "CFG",
        "KEY",
        "STT",
        "NTRS",
        "BRO",
        "CINF",
    ],
    "Industrials": [
        "CAT",
        "GE",
        "RTX",
        "HON",
        "UNP",
        "BA",
        "LMT",
        "DE",
        "UPS",
        "ETN",
        "NOC",
        "GD",
        "EMR",
        "CSX",
        "NSC",
        "FDX",
        "WM",
        "ITW",
        "MMM",
        "PH",
        "TT",
        "JCI",
        "CMI",
        "PCAR",
        "ROK",
        "CARR",
        "OTIS",
        "CTAS",
        "FAST",
        "AME",
        "DOV",
        "IR",
        "XYL",
        "EFX",
        "VRSK",
        "BR",
        "RSG",
        "WAB",
        "ODFL",
        "EXPD",
        "JBHT",
        "TXT",
        "HWM",
        "PWR",
    ],
    "Energy": [
        "XOM",
        "CVX",
        "COP",
        "SLB",
        "EOG",
        "MPC",
        "PSX",
        "VLO",
        "OXY",
        "WMB",
        "KMI",
        "HES",
        "OKE",
        "DVN",
        "FANG",
        "HAL",
        "BKR",
        "CTRA",
        "TRGP",
    ],
    "Materials": [
        "LIN",
        "APD",
        "SHW",
        "ECL",
        "FCX",
        "NEM",
        "DOW",
        "NUE",
        "DD",
        "CTVA",
        "PPG",
        "VMC",
        "MLM",
        "ALB",
        "IFF",
        "LYB",
        "STLD",
        "PKG",
        "AMCR",
        "IP",
        "CF",
        "EMN",
    ],
    "Utilities": [
        "NEE",
        "DUK",
        "SO",
        "D",
        "AEP",
        "SRE",
        "EXC",
        "XEL",
        "ED",
        "PEG",
        "WEC",
        "ES",
        "AEE",
        "DTE",
        "ETR",
        "FE",
        "PPL",
        "CMS",
        "CNP",
        "ATO",
        "NI",
        "LNT",
    ],
    "Real Estate": [
        "PLD",
        "AMT",
        "EQIX",
        "WELL",
        "SPG",
        "PSA",
        "O",
        "CCI",
        "DLR",
        "VICI",
        "EXR",
        "AVB",
        "EQR",
        "INVH",
        "VTR",
        "ARE",
        "MAA",
        "ESS",
        "KIM",
        "UDR",
        "REG",
        "BXP",
    ],
}

# Best-effort primary listing venue (does not affect ingest/backfill/campaign).
_NASDAQ = {
    "AAPL",
    "MSFT",
    "NVDA",
    "AVGO",
    "AMD",
    "ADBE",
    "CSCO",
    "INTC",
    "QCOM",
    "TXN",
    "AMAT",
    "INTU",
    "AMGN",
    "ISRG",
    "ADI",
    "LRCX",
    "MU",
    "KLAC",
    "SNPS",
    "CDNS",
    "MCHP",
    "FTNT",
    "MPWR",
    "CDW",
    "NXPI",
    "TER",
    "PTC",
    "GOOGL",
    "GOOG",
    "META",
    "NFLX",
    "TMUS",
    "CMCSA",
    "CHTR",
    "EA",
    "TTWO",
    "AMZN",
    "TSLA",
    "SBUX",
    "BKNG",
    "ORLY",
    "ROST",
    "AZO",
    "PCAR",
    "PAYX",
    "COST",
    "PEP",
    "MDLZ",
    "MNST",
    "KDP",
    "KHC",
    "DLTR",
    "VRTX",
    "REGN",
    "IDXX",
    "DXCM",
    "ALGN",
    "HOLX",
    "BIIB",
    "GILD",
    "ODFL",
    "FAST",
    "EXPD",
    "JBHT",
    "WBD",
    "LYV",
    "VRSK",
    "ANSS",
    "EBAY",
    "EXPE",
    "ULTA",
    "DPZ",
    "WDC",
    "STX",
    "NTAP",
    "GRMN",
    "CTAS",
    "XEL",
    "EXC",
    "AEP",
}


def build_contracts() -> dict[str, dict[str, object]]:
    contracts: dict[str, dict[str, object]] = {}
    seen: set[str] = set()
    for sector, tickers in SECTOR_TICKERS.items():
        for symbol in tickers:
            if symbol in seen:
                continue
            seen.add(symbol)
            uid = str(uuid.uuid5(NS, symbol))
            contracts[uid] = {
                "symbol": symbol,
                "exchange": "SMART",
                "primary_exchange": "NASDAQ" if symbol in _NASDAQ else "NYSE",
                "currency": "USD",
                "sec_type": "STK",
                "asset_class": "EQUITY",
                "sector": sector,
                "active": True,
                "lot_size": 1,
                "con_id": 0,
                "adv_shares_20d": 2_000_000,
                "last_close": 100.0,
            }
    return contracts


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a curated US-equity universe.")
    parser.add_argument("--out", default="infra/config/universe_300.json")
    args = parser.parse_args()

    contracts = build_contracts()
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(contracts, indent=2), encoding="utf-8")

    by_sector: dict[str, int] = {}
    for spec in contracts.values():
        sector = str(spec["sector"])
        by_sector[sector] = by_sector.get(sector, 0) + 1
    print(f"Wrote {len(contracts)} contracts to {out_path}")
    for sector, count in sorted(by_sector.items(), key=lambda kv: -kv[1]):
        print(f"  {sector}: {count}")
    print("NOTE: con_id is 0 — resolve via IB reqContractDetails before live/paper routing.")


if __name__ == "__main__":
    main()
